// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWorkflowHubAdmin.ContextModels;

public partial class TCategory
{
    public int FCategoryNumber { get; set; }

    public string FCategoryName { get; set; }

    public virtual ICollection<TArticle> TArticles { get; set; } = new List<TArticle>();
}