// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWorkflowHubAdmin.ContextModels;

public partial class TLectureRecord
{
    public int FLecRecordId { get; set; }

    public int FLectureId { get; set; }

    public int FMemberId { get; set; }

    public string FPhone { get; set; }

    public string FEmail { get; set; }
}