// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWorkflowHubAdmin.ContextModels;

public partial class TMemberBankAccount
{
    public int FMemberBankId { get; set; }

    public int? FMemberId { get; set; }

    public string FBankAccountName { get; set; }

    public int? FBankAccount { get; set; }

    public string FFinianInstitutionsId { get; set; }

    public string FFinanInstitutionBranchId { get; set; }

    public string FFinanInstitutionsName { get; set; }
}