// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWorkflowHubAdmin.ContextModels;

public partial class TOrderDetail
{
    public int FOrdRecordId { get; set; }

    public int? FOrderId { get; set; }

    public bool? FIsCopy { get; set; }

    public decimal? FSubtotal { get; set; }

    public int? FSopid { get; set; }
}