// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWorkflowHubAdmin.ContextModels;

public partial class TPointRecord
{
    public int FPointRecordId { get; set; }

    public int? FMemberId { get; set; }

    public string FPointRecord { get; set; }

    public string FExplanation { get; set; }

    public string FRecordTime { get; set; }
}