// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWorkflowHubAdmin.ContextModels;

public partial class TReply
{
    public int FReplyId { get; set; }

    public int FMemberId { get; set; }

    public int FArticleId { get; set; }

    public string FReplyContent { get; set; }
}