// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWorkflowHubAdmin.ContextModels;

public partial class TSopJobItem
{
    public int FJobItemId { get; set; }

    public string FJobItem { get; set; }

    public int? FJobId { get; set; }

    public string FJob { get; set; }

    public string FJobClass { get; set; }

    public int? FJobItemSort { get; set; }
}