// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWorkflowHubAdmin.ContextModels;

public partial class TSopItem
{
    public int FSopitemId { get; set; }

    public int? FSopid { get; set; }
}