// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWorkflowHubAdmin.ContextModels;

public partial class TSopProduct
{
    public int FSopProductId { get; set; }

    public int? FOrderId { get; set; }

    public int? FSopid { get; set; }

    public decimal? FPrice { get; set; }
}