// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWorkflowHubAdmin.ContextModels;

public partial class TSopIndustry
{
    public int FIndustryId { get; set; }

    public string FIndustry { get; set; }

    public int FIndustryClassId { get; set; }

    public string FIndustryClass { get; set; }

    public int? FIndustrySort { get; set; }
}