// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apiWorkflowHub.ContextModels;

public partial class TOrder
{
    public int FOrderId { get; set; }

    public int? FMemberId { get; set; }

    public decimal? FTotalPrice { get; set; }

    public DateTime? FOrderDate { get; set; }

    public bool? FOrderStatus { get; set; }

    public string FPayment { get; set; }
}