// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apiWorkflowHub.ContextModels;

public partial class TPublisher
{
    public int FPublisherId { get; set; }

    public int FMemberId { get; set; }

    public string FPubName { get; set; }

    public string FPubDescription { get; set; }

    public byte[] FPubImage { get; set; }

    public string FPubImagePath { get; set; }

    public string FPubStatus { get; set; }

    public string FPubCreateTime { get; set; }

    public string FPubLink { get; set; }
}