// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apiWorkflowHub.ContextModels;

public partial class TShare
{
    public int FShareId { get; set; }

    public int FMemberId { get; set; }

    public int FArticleId { get; set; }

    public string FShareUrl { get; set; }
}