// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apiWorkflowHub.ContextModels;

public partial class TShoppingCart
{
    public int FCartId { get; set; }

    public int? FMemberId { get; set; }

    public int? FSopid { get; set; }

    public decimal? FPriceId { get; set; }
}