// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apiWorkflowHub.ContextModels;

public partial class TSop
{
    public int FSopid { get; set; }

    public int? FMemberId { get; set; }

    public int? FPublisherId { get; set; }

    public byte? FSopType { get; set; }

    public string FSopName { get; set; }

    public string FSopDescription { get; set; }

    public byte[] FSopFlowImage { get; set; }

    public string FSopFlowImagePath { get; set; }

    public byte[] FPubSopImage { get; set; }

    public string FPubSopImagePath { get; set; }

    public int? FJobItemId { get; set; }

    public int? FIndustryId { get; set; }

    public string FBusiness { get; set; }

    public string FCustomer { get; set; }

    public string FCompanySize { get; set; }

    public string FDepartment { get; set; }

    public string FShareUrl { get; set; }

    public string FEditTime { get; set; }

    public string FSharePermission { get; set; }

    public int? FShareTargetId { get; set; }

    public string FFileStatus { get; set; }

    public decimal? FPrice { get; set; }

    public decimal? FSalePoints { get; set; }

    public string FPubContent { get; set; }

    public string FReleaseTime { get; set; }

    public string FReleaseStatus { get; set; }

    public string FProductUrl { get; set; }

    public bool? FIsRelease { get; set; }
}