// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apiWorkflowHub.ContextModels;

public partial class TSopAffix
{
    public int FSopaffixId { get; set; }

    public int? FSopid { get; set; }

    public string FAffixName { get; set; }

    public string FAffixPath { get; set; }
}