// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apiWorkflowHub.ContextModels;

public partial class TSopJob
{
    public int FJobId { get; set; }

    public string FJob { get; set; }

    public int FJobClassId { get; set; }

    public int? FJobSort { get; set; }
}